<?php
$quotes = array(
"amas a Jehová más que a mí",
"oras conmigo todas las noches",
"siempre sacas a Pancake por las noches porque sabes que no me gusta",
"valoras y cuidas a mis padres",
"me ayudas a tomar decisiones sin imponer las tuyas",
"respetas mis opiniones",
"me escuchas cuando hablo de cosas raras",
"me cuentas cosas interesantes",
"me aguantas cuando estoy de mal humor",
"me quieres aunque sea un poco rarita",
"te gusta darme la mano al caminar",
"me encanta tu sonrisa",
"estás muy guapo con el pelo canoso",
"you have style on your face ;)",
"tratas muy bien a las hermanas mayores",
"trabajas muy duro en la congregación",
"valoras mis sugerencias para tus discursos",
"me haces reír hasta que se me saltan las lágrimas",
"te hacen gracia mis tonterías",
"sé que siempre me vas a querer",
"eres mi Mike",
"sé que puedo confiar en ti",
"eres muy paciente conmigo",
"me escuchas aun cuando el tema no te interesa demasiado",
"me haces feliz",
"me das espacio",
"me dejas jugar a Los Sims tranquila :)",
"pones a los demás primero",
"te esfuerzas siempre por mantener la paz",
"me das consejo cuando me hace falta",
"no te importa que sea diferente",
"eres como un niño grande",
"me enseñas cosas",
"lo pasamos genial juntos",
"no pospones las decisiones",
"sabes cómo hacerme sentir mejor",
"eres un geek",
"me perdonas",
"me haces querer ser mejor persona",
"nunca te cansas de mí",
"te gusta ver shows coreanos conmigo",
"eres agradecido",
"siempre me dices que me quieres",
"me tratas como una reina",
"me has permitido entrar en tu mente",
"eres un quieris",
"no eres un gastis",
"hueles rico",
"tienes una excelente rutina espiritual",
"nunca me canso de tu compañía",
"te gusta estar conmigo",
"te gusta probar cosas nuevas conmigo",
"confías en mí",
"te gusta contarme cosicas",
"siempre tienes un pensamiento bíblico que compartir",
"me dejas quererte",
"me mandas unos gifs muy chulos",
"me haces visitas en mi oficina",
"me gusta cuando salimos a caminar",
"cantas canciones muy buenas",
"bailas para mí y para Pancake",
"te inventas canciones muy buenas",
);

$count_quotes = count($quotes)-1;
$random_quote = $quotes[rand( 0, $count_quotes )];